### ISSUE TITLE
Wrong permissions on /var/gavo/logs

### ISSUE THREAD

**Issue by BaptisteCecconi** [chbrandt/docker-dachs#11]
After deploying DaCHS (with the all-in-one option), and trying to start the server, we get a permission error related to the `/var/gavo/logs` directory. This directory indeed belongs to `root:root` instead of `dachsroot:gavo`. Fixing the permissions solves the issue.

**Comment by msdemlei** [comment]
On Fri, May 31, 2019 at 05:35:39AM -0700, Baptiste Cecconi wrote:
> After deploying DaCHS (with the all-in-one option), and trying to
> start the server, we get a permission error related to the
> `/var/gavo/logs` directory. This directory indeed belongs to
> `root:root` instead of `dachsroot:gavo`. Fixing the permissions
> solves the issue.

Umm, my two cents: I'm totally in favour of letting dachs init create
these directories (which probably is going to be tricky when
/var/gavo is in a third container, which I'd consider highly
desirable; but still).  You won't have further trouble like these
then (well, you will if *I* mess up, but then the blame is mine:-).

I don't remember how you do these things right now, but in
https://svn.ari.uni-heidelberg.de/svn/integration/dockerbased/upgrade-beta
there's an example for how to run dachs init at container build time,
which should do the trick of letting DaCHS build the file system
hierarchy.

Let me know if I should try a closer look...

           -- Markus

**Comment by chbrandt** [comment]
@BaptisteCecconi , do you still have this problem.

**Comment by chbrandt** [comment]
As of Dachs-on-Docker v2.1 things are working fine:
```
root@7a91b6871366:/var/gavo# ls -lh
total 28K
drwxrwxr-x 2 dachsroot gavo 4.0K Jul 14  2020 cache
drwxrwxr-x 2 dachsroot gavo 4.0K Jul 14  2020 etc
drwxrwxr-x 3 dachsroot gavo 4.0K Jul 14  2020 inputs
drwxrwxr-x 2 dachsroot gavo 4.0K Jul 14  2020 logs
drwxrwxr-x 2 dachsroot gavo 4.0K Jul 14  2020 state
drwxrwxr-x 2 dachsroot gavo 4.0K Jul 14  2020 tmp
drwxrwxr-x 4 dachsroot gavo 4.0K Jul 14  2020 web
```
(chbrandt/dachs:2.1): sha256:ee112a45b8b2140db072f0bd58ba2263c3a3cf196cf77dcad315b47c1897dc82

**Comment by BaptisteCecconi** [comment]
I didn't try recently. @lesidaner ad his colleague P. Hamy are in charge, but it seems they don't have this issue.
