### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by roipoussiere** [chbrandt/docker-dachs#7]
There is a list of dead links on this repository along with assumptions for a replacement.

# On readme.md

> The **docker-compose file** is available at the master branch. Suppose you have the **docker-compose.yml** in your current directory, just type the following command to have the service running:

The two links are [dead](https://github.com/chbrandt/docker-dachs/tree/master/dockerfile/data) and should be [alive](https://github.com/chbrandt/docker-dachs/blob/master/docker-compose.yml).

> If you want to see further details about running DaCHS on Docker without the compose, take a look at **Further ways of running Dachs**.

[dead](https://github.com/chbrandt/docker-dachs/blob/master/further-ways-of-running-dachs) -> [alive](https://github.com/chbrandt/docker-dachs#further-ways-of-running-dachs).

> dachs:data is here to provide a starting point -- it is an example for inserting the data as volumes into the framework. The contents can be seeing here, at **the Dockerfile**.

[dead](https://github.com/chbrandt/docker-dachs/tree/master/dockerfile/data) -> [alive](https://hub.docker.com/r/chbrandt/dachs/~/dockerfile/).

# On the Wiki page

> A first try on dockerizing DaCHS can be taken from the **Docker hub** (the respective Dockerfile is linked from there). There you have dachs and postgres servers running all together. Current version is v0.2.

[dead](https://hub.docker.com/r/chbrandt/dachs-server/) -> [alive](https://hub.docker.com/r/chbrandt/dachs/).

> I understand the very same image, for instance **chbrandt/dachs-server**, can be used as base image for the new ones. 

[dead](https://hub.docker.com/r/chbrandt/dachs-server/) -> [alive](https://hub.docker.com/r/chbrandt/dachs/).

**Comment by chbrandt** [comment]
Awesome :+1: 
Thanks
