### ISSUE TITLE
error in q.rd

### ISSUE THREAD

**Issue by mgangloff** [chbrandt/docker-dachs#9]
Executing DaCHS on Docker tutorial , the workflow example first command §5 
 $ docker exec -t dachs gavo import /var/gavo/inputs/arihip/q.rd
*** Error: At or near /var/gavo/inputs/arihip/q.rd, (21, 2): At
/var/gavo/inputs/arihip/q.rd, (21, 2): resource elements have no
coverage attributes or children.

**Comment by ytsapras** [comment]
Oh, shucks.  coverage is only available from DaCHS 1.1 on, and 1.1 is still in beta.  Since that
particular coverage element is fairly non-informative anyway, I'll comment it out for now.

Thanks for reporting.

**Comment by msdemlei** [comment]
(last comment by me, not Yannis; sorry about this, hadn't realised my browser still used his credentials)
